# Generated by Django 5.2 on 2025-04-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_businessunit_profile_user_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='image_capture',
            field=models.FileField(default=1, upload_to='media/attendance/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='management.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='management.profile'),
        ),
    ]
