# Generated by Django 5.2 on 2025-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_attendance_image_capture_alter_requirement_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
