# Generated by Django 5.2 on 2025-04-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_attendance_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip', models.FileField(blank=True, null=True, upload_to='media/Documents/payslip/')),
                ('exp_documents', models.FileField(blank=True, null=True, upload_to='media/Documents/exp_documents/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='media/Documents/offer_letter/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='media/Documents/pan_card/')),
                ('aadhar_card', models.FileField(upload_to='media/Documents/aadhar_card/')),
                ('mark_sheet', models.FileField(upload_to='media/Documents/mark_sheet/')),
                ('documents_title', models.CharField(max_length=55)),
                ('other_documents', models.FileField(upload_to='media/Documents/other_documents/')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='management.profile')),
            ],
        ),
    ]
